# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual

after_success:
  - Rscript -e 'covr::codecov()'
